# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: make build
    - id: path
      run: echo "path=$(swift build --configuration release --show-bin-path)" >> "$GITHUB_OUTPUT"
    - uses: actions/upload-artifact@v4
      with:
        name: binary
        path: ${{ steps.path.outputs.path }}/top-notch
